### ISSUE TITLE
Allow snapshot creation on an encrypted volume 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1470]
# Describe the bug #

At present, snapshot creation is blocked on a volume which is already encrypted. The reason to disallow this operation was to avoid the possibilities of the  attack   on encryption key.  

Considering our current snapshot implementation create a new CLONED volume in backend , I feel, we can use a new key for the snapshot volume. However we have to figure out the the possibile solutions on this.

@vasyl-purchel please share your thoughts as well.

**Comment by vasyl-purchel** [comment]
hi @humblec, I haven't followed much on how snapshots are created, but if I'm getting it right, cloning doesn't mean copying over data from one volume to another but actually cloning the volume. in order to use new key it would require to implement re-encryption, which is not currently done... we haven't looked into that yet...

also I'm not sure how snapshot is linked to the original volume... but I believe it shouldn't be an issue if volume is re-encrypted as it will have separate key in kms meaning from encryption point of view it doesn't need to have any relationship with original volume.

**Comment by dillaman** [comment]
Technically, if you don't re-encrypt the full volume after the creation of each snapshot (or similarly for each create-from-snapshot / create-from-volume call), yes, it's possible to brute-force the master encryption key (e.g. known plaintext attacks). 

For example, cloud providers (like GCE) say that snapshots will be "full" snapshots if your volumes are encrypted [1].

[1] https://cloud.google.com/compute/docs/disks/customer-supplied-encryption#create_snapshot

**Comment by vasyl-purchel** [comment]
yes, that's pretty much what I was thinking of also - they also mention you must specify new encryption key, so in case of using kms instead of a single key from k8s secrets we could go similar way as with creating new disk - create new encryption key, make a full copy of existing volume (with all the metadata attached I guess) and then re-encrypt it with a new key

although I know it is possible to brute-force the master key for the first pass probably it can be done without re-encryption with a note on  that in documentation (i.e. if you create one-two copies it  won't make it brute-forceable, but if you create automatically snapshots every day or smth - do it at your own risk :) ) but for feature parity with other storage providers - make sense to have as soon as possible.

**Comment by humblec** [comment]
@vasyl-purchel indeed we are planning to consider the scenario of using KMS with Vault configuration. The kube secret way is not scalable or its not what we want to really consider for enterprise customers/users. So we will be giving or kind of defaulting to KMS+ Vault configuration .. 

This is the process we follow for snapshot creation:

``` https://github.com/ceph/ceph-csi/pull/1160#issue-432402214

Create a temporary snapshot from the parent volume

Clone a new image from a temporary snapshot with options --rbd-default-clone-format 2 --image-feature layering,deep-flatten

Delete temporary snapshot created

Create snapshot from clone image
```


So the volumesnapshot is carved out from the  'new' cloned image. Encrypting it with the new key would be the ideal and  in parity with the industry standards I believe.  Also, IMO, first pass brute force of master key can be kept aside or we dont have to worry about it atleast in first phase.

**Comment by Madhu-1** [comment]
We also need to support PVC-PVC cloning

**Comment by humblec** [comment]
Considering the discussions so far on this: 

*)  While we create a new image ( image from temp snapshot of source image) at time of snapshot we will **reencrypt it with different key.** 
*) while we clone PVC to a new PVC the same process of **reenryption with a different key** can be performed.

One question I have here is, if we have a new key encrypted data on snapshotted or cloned volume , will it cause any issues while we perform flattening in the backend or while moving/removing it on/from trash?  

@vasyl-purchel @dillaman thoughts ?

**Comment by vasyl-purchel** [comment]
I don't think it should cause any issues as pointer to the key in kms is stored along with the image, so snapshot/clone image will have a pointer to another key, once deleted - you delete a pointer, no one cares of the key itself but would be good to remove it also from kms just to not leave it behind.

although I don't know how "moving" is done as currently key is stored in kms by volume id I believe so if it changes on move - there can be an issue of loosing the key...
