### ISSUE TITLE
security hardening volume mounts

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#1487]
# Describe the feature you'd like to have #

For volumes, it would be great of a ceph user with limited rights to mount that one volume was created for each volume dynamically created. This would help security when a single node is compromised. Only the volumes already mounted on that host would be accessible, not all volumes in the cluster.

**Comment by Madhu-1** [comment]
@kfox1111 can you provide the link to the ceph docs is it possible to have these capabilities for a single user?

Note:- creating a new user for a indivisual subvolumes is not a great idea.

CC @ShyamsundarR

**Comment by kfox1111** [comment]
Why do you consider it not a great idea?

The reasons for that need to balance against the not great idea of allowing any node in the cluster to mount any volume.

**Comment by ShyamsundarR** [comment]
@kfox1111 CSI 1.0 had the option to add a per PV cephx credential for CephFS. The deal though was that, we still needed the node stage secret, to access per PV credentials to then pass them to the required operations. Which sort of defeats the node compromise situation, as now the compromised node has access to the node stage secret, which can be used to fetch all required credentials for all PVs.

The above was discussed here: https://github.com/ceph/ceph-csi/pull/437

If we need to provide a scheme that needs to limit the compromise radius, then we need to do some plumbing to provide the node operations the generated per-PV credential, instead of the global CSI node stage credentials.

Further if the nodeplugin can fetch any such per-PV credential (which it has to as any PV can be mounted to any node), then from the compromised nodes nodeplugin pod it is feasible to fetch all such credentials, again not providing the security hardening that is desired.

Thoughts?

**Comment by kfox1111** [comment]
Something's wrong I think if you need a k8s secret that can access all the pv secrets for all of the nodes. There needs to be a way to restrict access to the pv's secrets just to the nodes on which they are assigned. I would have figured the NodeRestriction
admission controller would do that, but maybe not. This is a long standing problem in K8s I think where you need to have support daemonsets to enhance k8s but need to restrict those pods to only be able to operate on the node its running on. Should this be brought up to some SIG?
