### ISSUE TITLE
Cephfs: check ENOTEMPTY in  DeleteVolume for subvolumes having snapshots

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1491]
Currently, if the subvolume has the snapshots and the `--retain-snaps`feature is not present on the subvolume we will attempt for the subvolume deletion, due to this from the logs its not clear why the subvolume deletion is failing.
Incase `--retain-snaps` feature is not present we should check for the snapshots to give better error message to the user.

**Comment by Madhu-1** [comment]
cc @ShyamsundarR @humblec  @agarwal-mudit @Yuggupta27

**Comment by ShyamsundarR** [comment]
The error returned when snapshots are present and the subvolume is attempted to be deleted (without the `--retain-snapshots` or due to older subvolume version) is ENOTEMPTY. This error can be inspected to throw an appropriate log message, rather than look at snapshot count from the CSI plugin to show a relevant error message.

The entire message is, `subvolume <subvolumename> has snapshots`

**Comment by Madhu-1** [comment]
Yes above looks good thanks @ShyamsundarR
