### ISSUE TITLE
Is there a plan to add rbd csimigration controller in kubernetes?

### ISSUE THREAD

**Issue by huchengze** [ceph/ceph-csi#1725]
# Describe the feature you'd like to have #

Add rbd csimigration controller in kubernetes. 

# What is the value to the end user? (why is it a priority?) #

If CSI Migration is working properly, Kubernetes end users shouldn’t notice a difference. After migration, Kubernetes users may continue to rely on all the functionality of in-tree storage plugins using the existing interface.

# How will we know we have a good solution? (acceptance criteria) #

[This package](https://github.com/gardener/gardener/tree/master/extensions/pkg/controller/csimigration) contains a generic CSI migration controller that helps provider extensions that are still using the legacy in-tree volume provisioner plugins to migrate to CSI.

# Additional context #

Some [in-tree storage plugins](https://github.com/kubernetes/kubernetes/blob/c1f36fa6f28d3618c03b65799bc3f58007624e5f/pkg/volume/csimigration/plugin_manager.go#L80) has already completed csimigration, and looks like there is no plan to add rbd csimigration controller in [kubernetes's blog](https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/#what-is-the-timeline-status).

**Comment by Madhu-1** [comment]
Currently, we don't have any plan to support migration.

@rootfs @gman0 any suggestion here?

**Comment by gman0** [comment]
No plans AFAIK, sorry.

**Comment by lwj5** [comment]
just to add, here's the link to the issue. https://github.com/kubernetes/enhancements/issues/625
Is there a possibility of relooking into this in the future when all ceph csi functionality is stable?

**Comment by Jiawei0227** [comment]
Hello guys. I am the lead of CSI migration feature in Kubernetes. I think as long as you guys are sure that no current customers are still using the in-tree ceph rbd and cephfs volume plugin then it is fine that you do not implement CSI migration.

Our plan moving forward is to remove the in-tree plugins. CSI migration is the feature in k8s that can support a smooth transition from in-tree usage to CSI usage for volume related operations. Without CSI migration and if the intree driver is removed. If any customer upgrading to the version without the driver. It might cause some problem for them for their existing volume.

I dont think you guys need a csimigration controller running. But mainly a translation logic in the core k8s to get it work.  If any of you guys are interested doing migration for ceph fs and rbd driver. Please feel free to ping me on slack in k8s or attend the CSI migration meeting.

cc @humblec I heard about you are interested in doing migration for ceph fs and rbd. I am wondering if this is still the case?

**Comment by Jiawei0227** [comment]
Here is a kubernetes issue opened by humble and he seems to be working on it: https://github.com/kubernetes/kubernetes/issues/91246

Can you guys sync up to make sure what is the plan moving forward? Thanks a lot!

**Comment by Madhu-1** [comment]
Migration cannot be supported due to  following reasons

With the new cephcsi design, the volumeHandle is the one unique to identify the backend volume, pool clusterID etc, AFAIK as with migration the  PV CSI volumeHandle is the rbd image/cephfs subvolume name. If we want to support we can support only mount/unmount and not even delete operation.

Below items are not supported if we migrate

* Expand PVC
* Create Snapshot
* Create Clone
* Delete Volume

**Comment by Madhu-1** [comment]
cc @nixpanic @humblec

**Comment by humblec** [comment]
> Migration cannot be supported due to following reasons
> 
> With the new cephcsi design, the volumeHandle is the one unique to identify the backend volume, pool clusterID etc, AFAIK as with migration the PV CSI volumeHandle is the rbd image/cephfs subvolume name. If we want to support we can support only mount/unmount and not even delete operation.
>

Just to summarize, these migrated volumes comes almost in the same state of `static volumes support` we provide here with CSI driver . Its one form and accepted mostly at times considering the origin of volumes/how its provisioned at very first stage.  In short thats the same case with static volumes today we offer. So, leaving advanced feature support on such volumes is fine .  

Even we could think about further treatment of advanced features by shaping it to new volume handle format on those volumes with an extra effort/code later. But, the main point of the discussion was that, is it a worth effort?  

Due to the long existence of this CSI driver and  external provisioner for Ceph  drivers, many users are out of in tree plugins any way. 

So, we are leaning towards mostly to mark the in tree driver for deprecation ( unless there is a strong community requirement) . but will double confirm it soon @Jiawei0227

**Comment by humblec** [comment]
With the community feedback and requirements this has been planned for kube v1.23 and kubernetes KEP is available here https://github.com/kubernetes/enhancements/issues/2923  . 

Reopening this issue as this has been getting worked on (https://github.com/ceph/ceph-csi/projects/18)  which should allow all existing in tree users to have a smooth migration path... we need few changes in the CSI driver too.
