### ISSUE TITLE
Is it possible to specify somewhere fs mount option umask?

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1987]
I was wondering if it is possible to supply the umask=0027 mount option somewhere. I am testing a bit with postgres, and it complains about the data having the incorrect permissions. I noticed the csc command line offering mount options

`
csc -e unix:///tmp/mesos-csi-uuh6Ra/endpoint.sock node stage --cap SINGLE_NODE_WRITER,mount,xfs,discard --staging-target-path '/mnt/staging' --vol-context 'clusterID=ceph,pool=app,volumeNamePrefix=app-' '0001-0004-ceph-0000000000000016-3d134ea2-9efe-11eb-ba5c-0050563001a1'`

Looks like the discard option is there

```
[@~]# mount | grep '/mnt/staging'
/dev/rbd0 on /mnt/staging/0001-0004-ceph-0000000000000016-3d134ea2-9efe-11eb-ba5c-0050563001a1 type xfs (rw,relatime,nouuid,attr2,discard,inode64,sunit=8192,swidth=8192,noquota,_netdev)
```

However when I exchange the discard, for the umask=0027 option I am getting this error

```
[3757544.074496] rbd: rbd0: capacity 100663296 features 0x1
[3757544.439959] XFS (rbd0): unknown mount option [umask=0027].
```
It looks like the umask option is used with the rbd device instead of used with the filesystem mount

**Comment by f1-outsourcing** [comment]
I incorrectly assumed that their should be an xfs umask/mode option. Which it has not. It does not have it because you can just chmod the mount and it will maintain these settings on remount.

Further investigating this I found this in the code
```

 319         if !readOnly {
    320                 // #nosec - allow anyone to write inside the target path
    321                 //err = os.Chmod(stagingTargetPath, 0777)
    322         }
```

I would like to know what design reasoning is behind this? This deviates from standards. I think this also makes it possible to generate some sort of denial of service on your tasks possible.

Now any process on the host can just do a dd if=/dev/zero of=/mnt/staging/0001-0004-ceph-9eeba5c-xxxxxx until the volume is full and your task dies and never will start because of the full volume.

**Comment by humblec** [comment]
>I would like to know what design reasoning is behind this? This deviates from standards. I think this also makes it possible to generate some sort of denial of service on your tasks possible.
Now any process on the host can just do a dd if=/dev/zero of=/mnt/staging/0001-0004-ceph-9eeba5c-xxxxxx until the volume is full and your task dies and never will start because of the full volume.
>

@f1-outsourcing we were facing issues with the cephfs mount ( one of them for manilla use cases)  , for example: permission denied on the mount ...etc in absence of it.  one of the option was spawning privileged pod in such scenarios . Considering `privilged` pod is not an option for solving such issues we were left with granting permissions with above way. 

Its not a good or full fledged solution, however regarding the deniel of service with `dd` example, one thing to note here, who got/gave access to the host ? if someone has access to host there could be different things one can do and security is pretty much compromised. 

If there are better solutions around, we would like to reconsider options instead of `chmod` , so please feel free to discuss / bring in if there is any.

**Comment by f1-outsourcing** [comment]
> @f1-outsourcing we were facing issues with the cephfs mount ( one of them for manilla use cases) , for example: permission denied on the mount ...etc in absence of it. one of the option was spawning privileged pod in such scenarios . Considering privilged pod is not an option for solving such issues we were left with granting permissions with above way.

So make a configuration option you can set this in. Do not set it as a default for everyone that uses the driver. The idea behind csi is you create a driver for storage, not to fix storage. If there is an issue, ceph needs to fix it.

> Its not a good or full fledged solution, however regarding the deniel of service with `dd` example, one thing to note here, who got/gave access to the host ? if someone has access to host there could be different things one can do and security is pretty much compromised.

I do not think we should debate the usefulness of linux userid's. Many more knowledgeable people have done this already in the past, resulting in the current design. 
There are still many processes that are run in this setup a CO node setup, like time synchronization or monitoring daemons. If even if you could vouch for all of them, you still have many sysadmin roles that can have console access, on breach there, and you could make some script that dd's all tasks in the CO.
