### ISSUE TITLE
[RBD] Support Regional DR for Encrypted PVC

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2032]
Currently, encryption is only supported for the PVC without mirroring., This issue is to track the support for encryption of mirrored PVC.

To complete the Whole DR story (failover and failback) the volume should be usable by the applications on the primary cluster. 

The KMS setup is something up to the admins how they want to handle it and how they want to migrate the information from one KMS instance to another during the failover and failback operation it is left to them.
 
We need to test all the different KMS we support in cephcsi.

**Comment by humblec** [comment]
@Madhu-1 https://github.com/ceph/ceph-csi/issues/2027 was about Testing encryption at mirroring setup, is this issue also on `testing` of encryption in a mirroring setup ? also,  can you please add some details about:  what is the final goal /target here or covered with this issue ?

Are we planning to support encryption from any KMS provider ( vault, AWS, secret based ..etc) ? or its limited to some ? if yes, what are those ?

Also are we planning to support both `failback` and `failover` cases with encryption ?

Does the source and destination clusters have access to same `key management system` in this context ?

...

Please add more details about the requirement..  so that we can also get volunteers for helping on the same accordingly.

**Comment by Madhu-1** [comment]
> @Madhu-1 #2027 was about Testing encryption at mirroring setup, is this issue also on `testing` of encryption in a mirroring setup ? also, can you please add some details about: what is the final goal /target here or covered with this issue ?
> 

#2027 was closed as a duplicate. This issue was opened as a tracker and I still need to update with more details.

> Are we planning to support encryption from any KMS provider ( vault, AWS, secret based ..etc) ? or its limited to some ? if yes, what are those ?
> 

We will come to know once we start testing it. and as a general idea if the KMS instance is the same across both clusters the encryption should work seamlessly

> Also are we planning to support both `failback` and `failover` cases with encryption ?
> 
IMO if we don't support both failover and failback this becomes pretty useless. and to complete the DR feature the volume should be in the useable state on the primary cluster.

> Does the source and destination clusters have access to same `key management system` in this context ?
> 

KMS is something set up by the admin outside of cephcsi. I assume its up to them how they want to handle it but we will document how this works in the DR documentation.
> ...
> 
> Please add more details about the requirement.. so that we can also get volunteers for helping on the same accordingly.

@humblec any volunteers to take it up?

**Comment by Madhu-1** [comment]
Assigning this to @Rakshith-R based on the discussion

**Comment by Rakshith-R** [comment]
:+1: i'll work on it.

**Comment by humblec** [comment]
As discussed we have to continue the analysis and get into the completion in upcoming releases. Moving this out of 3.4.0 release.
