### ISSUE TITLE
Support the object-map RBD image feature

### ISSUE THREAD

**Issue by andrew-farries** [ceph/ceph-csi#2084]
# Describe the feature you'd like to have #

I'd like `ceph-csi` to be able to create RBD images with the [object-map](https://docs.ceph.com/en/latest/rbd/rbd-config-ref/#image-features) feature enabled.

# What is the value to the end user? (why is it a priority?) #

My use case is that I have a K8S cluster used to run end-to-end tests of my application. A typical test run will create and delete ~100 500Gi RBD images and around the same number of snapshots.

Manual testing shows that RBD images with the `object-map` feature enabled are able to be deleted almost instantly - whereas the same image without the the feature takes minutes.

With multiple test runs happening per day, RBD images are being created faster than Ceph can delete them, thus I will eventually exhaust the space available in the cluster.

# How will we know we have a good solution? (acceptance criteria) #

Deletion of arbitrarily large RBD images should be fast, ie not in the order of minutes.

# Additional context #

I'm running the Ceph cluster via `rook-ceph`. 

[Rook docs](https://rook.io/docs/rook/v1.6/ceph-block.html) state that only the `layering` image feature is currently supported by `ceph-csi`.

[ceph-csi docs](https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md) state that `layering`, `exclusive-lock` and `journaling` are supported and that the required support for `object-map` is in recent kernels.

Deletion without `object-map`:

![image](https://user-images.githubusercontent.com/8225907/118279462-17738080-b4c3-11eb-8a8a-531a7689e020.png)

Deletion with `object-map`:

![image](https://user-images.githubusercontent.com/8225907/118279544-2ce8aa80-b4c3-11eb-9176-2489576e6ccf.png)

**Comment by Madhu-1** [comment]
> # Describe the feature you'd like to have
> I'd like `ceph-csi` to be able to create RBD images with the [object-map](https://docs.ceph.com/en/latest/rbd/rbd-config-ref/#image-features) feature enabled.
> 
> # What is the value to the end user? (why is it a priority?)
> My use case is that I have a K8S cluster used to run end-to-end tests of my application. A typical test run will create and delete ~100 500Gi RBD images and around the same number of snapshots.
> 
> Manual testing shows that RBD images with the `object-map` feature enabled are able to be deleted almost instantly - whereas the same image without the the feature takes minutes.
> 
> With multiple test runs happening per day, RBD images are being created faster than Ceph can delete them, thus I will eventually exhaust the space available in the cluster.
> 
> # How will we know we have a good solution? (acceptance criteria)
> Deletion of arbitrarily large RBD images should be fast, ie not in the order of minutes.
> 
> # Additional context
> I'm running the Ceph cluster via `rook-ceph`.
> 
> [Rook docs](https://rook.io/docs/rook/v1.6/ceph-block.html) state that only the `layering` image feature is currently supported by `ceph-csi`.
> 

Yes only layering is supported as rbd-nbd is not ready yet, we have issues  with rbdplugin container restart.

> [ceph-csi docs](https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md) state that `layering`, `exclusive-lock` and `journaling` are supported and that the required support for `object-map` is in recent kernels.
> 

This is for someone who wants to use this feature with known limitations. Even this is available with rook but not documented because of limitation.

> Deletion without `object-map`:
> 
> ![image](https://user-images.githubusercontent.com/8225907/118279462-17738080-b4c3-11eb-8a8a-531a7689e020.png)
> 
> Deletion with `object-map`:
> 
> ![image](https://user-images.githubusercontent.com/8225907/118279544-2ce8aa80-b4c3-11eb-9176-2489576e6ccf.png)


@andrew-farries in cephcsi we do the below operation to delete an image to have better performance of PV deletion at the kubernetes level

* Move the image to the trash
* Add a task to remove an image from the trash.

**Comment by MisterBlueBear** [comment]
Perhaps another example:
Our ceph-csi (with rook) is configured to provision volumes on an external ceph cluster (outside of K8s). The Ceph dashboard is not able to display metrics for data usage (provisioned space, total provisioned space, etc) because it requires fast-diff (actually, since ceph Nautilus, 'object-map' will implicitly enable 'fast-diff' and vice-versa).

What would be the downside to having the option to enable object-map / fast-diff' ?
