### ISSUE TITLE
RBD: Do flattening only the temporary cloned images not the images given to user for mapping

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2190]
In the case of CreateVolume from snapshot and CreateVolume from Volume, when the soft or hard limit is reached we do flattening on the image. and we need to ensure that we only flatten the intermediate clones we create not the volumes which might get mapped when the application mounts the PVC. flattening on the images can affect the read/write performance of the image due to some internal locking.

**Comment by Madhu-1** [comment]
This needs some testing and may or may not code changes but it's good to validate this case.

**Comment by humblec** [comment]
As discussed we have to continue the analysis and get into the completion in upcoming releases. Moving this out of 3.4.0 release.

**Comment by Rakshith-R** [comment]
In current implementation of CephCSI rbd driver,  flattening is triggered for two reasons hitting snaps and CloneDepth limit: 
Ceph CSI rbd processes(highly summarized): 
- k8s snapshot = PVC->snap->tmp-snap-img->snap
- k8s PVC-restore= Snapshot's snap->clone-img 
- k8s PVC-PVC-clone= PVC -> snap->temp-clone-img->snap->clone-img

(snap refers to rbd image snapshot)


With respect to snap limit: 
- rbd image snap is taken during k8s snapshot and pvc-pvc cloning.
- Thus flattening due to hitting snap limit can occur only on rbd temp image underlying snapshot and temp clone image underlying PVC-clone. 

With respect to CloneDepth limit: 
To be analysed.

 <details>
<summary></summary>
 Every k8s PVC's underlying image if it has a parent rbd image, it's either a k8s snapshot's image(PVC-restore) or temporary-clone image(PVC-PVC-clone).
 </details>

**Comment by Rakshith-R** [comment]
https://github.com/ceph/ceph-csi/blob/60c2afbccadf008ebcd1293f3c10f0d5596b0e62/internal/rbd/clone.go#L258-L290

If a temporary clone does not exist for given image ,
we need to find the parent image here, which would be a rbd image image under k8s snapshot and flatten it instead.

**Comment by Madhu-1** [comment]
> https://github.com/ceph/ceph-csi/blob/60c2afbccadf008ebcd1293f3c10f0d5596b0e62/internal/rbd/clone.go#L258-L290
> 
> If a temporary clone does not exist for a given image ,

In which case the temporary clone does not exists?

from PVC-PVC clone case both image and the temporary image will be deleted when we delete the image.

> we need to find the parent image here, which would be a rbd image image under k8s snapshot and flatten it instead.

Yes, the snapshot needs to be flattened in case of PVC restoration from snapshot operation.

**Comment by Rakshith-R** [comment]
> In which case the temporary clone does not exists?

I meant ErrImageNotFound for temp clone -> for a snapshot restored parent PVC.

**Comment by Rakshith-R** [comment]
@Yuggupta27 , I was planning to work on this. 
If you did understand the issue and the fix discussed above in the comments, then its fine
else let me know, I can continue and send a pr for this soon.

**Comment by Rakshith-R** [comment]
https://github.com/ceph/ceph-csi/blob/9c50e255fb4f2a3cad918db2c4e5a9af1696f38a/internal/rbd/controllerserver.go#L588-L595

one more place where we are flattening the image which will be given to user for mapping. 
The parent underlying  snapshot image can be flattened instead.
