### ISSUE TITLE
external encryption/decryption of passphrase

### ISSUE THREAD

**Issue by tareksha** [ceph/ceph-csi#2209]
# Describe the feature you'd like to have #

I'm trying to find the best method for integrating an external encryption service into the encryption flow of ceph-csi in a manner that also allow me to rotate the keys and invalidate them externally, just like the hard-coded `aws-metadata`. `aws-metadata` itself is not an option because the solution must be hyperscaler-agnostic. `vault` and `vaulttoken` are not possible either because they store the passphrase in the KV as-is.

We don't really have to establish a REST-like contract and take the burden of all the derived security aspects. Maybe we can pick a per-volume encryption key from a kubernetes secret based on a predefined mapping scheme.

# What is the value to the end user? (why is it a priority?) #

Allow integrating any key management service into the encryption flow. This is very useful for solutions that rely on in-house services for managing sensitive customer data.

# How will we know we have a good solution? (acceptance criteria) #

A volume encryption type in ceph-csi that interacts with a custom service that encrypts/decrypts the passphrase and stores the encrypted passphrases in RBD metadata, just like `aws-metadata` does.

# Additional context #

**Comment by nixpanic** [comment]
I expect that implementing this should not be very difficult, different KMS providers already have the majority functionality that is needed, but it needs to be combined into a new KMS provider.

SecretsMetadataKMS uses a passphrase from the StorageClass Secret to encrypt a per Volume key:

https://github.com/ceph/ceph-csi/blob/5aca04d540744110aaf160e191b096e5584f9c86/internal/util/secretskms.go#L94-L96

The VaultTokens KMS fetches a Token from a Secret of the Tenant (a Kubernetes Namespace):

https://github.com/ceph/ceph-csi/blob/5aca04d540744110aaf160e191b096e5584f9c86/internal/util/vault_tokens.go#L43-L49

Combining the logic of the two should make it possible to:

1. have a master key (KEK) in a Secret (could be in a given Namespace, or per Tenant), a single one or one per PVC
2. store the data-encryption-key (DEK, passed to `cryptsetup`/LUKS) encrypted by the KEK in the RBD-metadata

If you are willing to develop such a feature, please start with proposing a design document similar to [docs/design/proposals/encryption-with-vault-tokens.md](https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/encryption-with-vault-tokens.md) so that we can discuss more details. It might be useful to use https://hackmd.io or an other document collaboration service to get early feedback.

**Comment by tareksha** [comment]
Thanks @nixpanic, this is exactly my intention! an encrypted DEK in RBD metadata that is decrypted by a per-volume KEK. i'll proppse a design asap.
