### ISSUE TITLE
Improve contribution workflow to speed up issue tracking and PR merging

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2367]
This proposal aims to improve the workflow for accepting contributions to the project.

## Current Bottlenecks

Maintainers of the project are the only ones that can add labels to issues and PRs, update project boards and manage the merging of PRs.

## Suggested Improvement

There is a group of _core-contributors_ that regularly

- handles reported Issues
- send PRs
- reviews PRs
- works on Issues and PRs associated with different project boards

It would be beneficial for the Ceph-CSI project that the _core-contributors_ get the privileges

- to assign labels to Issues and PRs
- have their PR reviews count
- update project boards

PRs should get merged when there is a approved review of a _core-contributor_ and at least one _maintainer_. This will improve the velocity of merging PRs, as currently two _maintainers_ need to approve PRs. The approvals of _core-contributors_ are not counted by Mergify and only used as input for the review of _maintainers_.

## Required Changes

By using GitHub teams, Mergify can be configured to require a review from a _core-contributor_ and a _maintainer_.

### GitHub Settings

There need to be two GitHub teams:

- a team `core-contributors` with `write` permissions
- a team `maintainers` with `write` permissions

A _maintainer_ should be part of both teams, as the _maintainer_ is still a _core-contributor_. It might be possible to make the `maintainers` team a sub-team of `core-contributors`.

### Mergify Rules

The current `#approved-reviews-by>=2` rule will allow two approvals from _core-contributors_ once the team has been created. This is not what we want, as at least one approval needs to come from a _maintainer_.

https://github.com/ceph/ceph-csi/blob/1dc032e5545cd5296b272e755aeda5d6bf4c9af5/.mergify.yml#L35-L57

The above rule (and duplicates) needs to get adjusted to:

```yaml
  - name: automatic merge
    conditions:
      - label!=DNM
      - base~=^(devel)|(release-.+)$
      - approved-reviews-by=@core-contributors
      - approved-reviews-by=@maintainers
      - "#changes-requested-reviews-by=0"
```

- `approved-reviews-by` is a list as described in the [attributes](https://docs.mergify.io/conditions/#attributes)
- contents of lists are [matched with a simple `=`](https://docs.mergify.io/conditions/#how-to-match-lists)

**Comment by Madhu-1** [comment]
Thanks, @nixpanic. This looks to be a good suggestion at least this helps in a couple of ways from my point of view

* Better sprint planning (creating boards, Moving issues, labeling issues, etc) and avoid burden on maintainers
* Helps for the better review process and PR's will get merge on time and smooth transition
* Getting help from team on issue handling and Release
* More team involvement

CC @humblec @ShyamsundarR @agarwal-mudit

**Comment by pkalever** [comment]
Sounds like a good plan to me :+1:

**Comment by Madhu-1** [comment]
cc @pkalever @Yuggupta27 @yati1998 @Rakshith-R

**Comment by Yuggupta27** [comment]
Really great step! It will definitely help to smoothen the flow as well as make the review/triage process faster!

**Comment by Rakshith-R** [comment]
Looks good to me too ! :+1:

**Comment by ShyamsundarR** [comment]
LGTM! (adding a triage group is useful (triage to include counting review votes))

**Comment by humblec** [comment]
Thanks @nixpanic , indeed the maintainers have burden now with respect to handling many things at hand and we have to come out of this situation one by one. Thats one of the reason for me to also propose more maintainers to the project https://github.com/ceph/ceph-csi/issues/1922 ( which didnt get in for some reason) ...etc. Regardless, indeed we have to take a different route on atleast process like PR review , releases....etc.. In short,  as always I am more welcoming here to improve the process!

Few things which I would like to clarify here, 

iic, github roles/permissions can be associated with a user on below filters:

```
Read
Triage
Write
Maintain
Admin
```

At present ( unless some changes were happened in between) , we have below maintainers with the CSI project and all have `write` access to the repo.
 
@gman0 @nixpanic @ShyamsundarR @Madhu-1 @agarwal-mudit and myself .

All other contributors are with `read access`:

I also have `admin` access to this repo along with other 'ceph' org admins like @leseb .

>

    a team core-contributors with write permissions
    a team maintainers with write permissions
>

Sure,  Above proposal looks good to me. One question I have here is, 

Is `write` access good enough for `maintainers` or do we need to grant `admin` access for all maintainers ? what I have noticed  is that,  `write` access is more than good enough for almost all repo handling processes.

So, either we will have all maintainers to `admin` access or stick to  all maintainers  with `write` access. I am fine with any model, but would like to have some process/consistency across, so putting it across.

Also, do we need to explore other filters like `maintain` among the proposed groups of `core contributors/maintainers'...etc? 

Regarding approval count for merging : one small change which I can propose here is:

1) either `one maintainer` + `2  core contributors` 
or
2) `2 maintainers approval` 

Otherwise if we go ahead with current proposal of merge,  isnt it pretty much same that the approval is having same effect regardless its coming from maintainer or core contributor. 

Again, please share the thoughts ,  I can make the changes accordingly.

**Comment by nixpanic** [comment]
`write` permissions seem to be sufficient for _maintainers_ to do releases.

Additional _admins_ might be useful, but that is out of scope for this request. A group with the _admins_ is of course easiest to use in case we want additional checks or request attention from _admins_ in an Issue or PR (using `@ceph-csi-admins`).

> either `one maintainer` + `2 core contributors`

This is difficult to express with Mergify rules. I also do not think there is any benefit in requiring a 2nd _core-contributor_ review. If under reviewed PRs get merged and cause issues, we can fix or revert them if needed.

**Comment by nixpanic** [comment]
Proposed teams, based on current contributions:

**Ceph-CSI-Contributors** (includes all maintainers too)
 - @Madhu-1
 - @Rakshith-R
 - @ShyamsundarR
 - @Yuggupta27
 - @agarwal-mudit
 - @humblec
 - @nixpanic
 - @pkalever
 - @yati1998

**Ceph-CSI-Maintainers**
 - @Madhu-1
 - @humblec
 - @nixpanic

**Comment by agarwal-mudit** [comment]
LGTM

**Comment by Madhu-1** [comment]
https://github.com/orgs/ceph/teams/ceph-csi-contributors and https://github.com/orgs/ceph/teams/ceph-csi-maintainers team are created with write and admin access. Thanks to @leseb for helping on creating the teams.

 @nixpanic can please you send a PR to make sure of it?

**Comment by humblec** [comment]
> Proposed teams, based on current contributions:
> 
> **Ceph-CSI-Contributors** (includes all maintainers too)
> 
>     * @Madhu-1
> 
>     * @Rakshith-R
> 
>     * @ShyamsundarR
> 
>     * @Yuggupta27
> 
>     * @agarwal-mudit
> 
>     * @humblec
> 
>     * @nixpanic
> 
>     * @pkalever
> 
>     * @yati1998
> 
> 

@nixpanic I propose to include @gman0 on the contributors team as he is still around and been a good contributor to this repo. 
@leseb can we add him to contributors team?

**Comment by humblec** [comment]
@Madhu-1 I think above comment ( updating the contribuotrs team) is yet to be addressed..

**Comment by Madhu-1** [comment]
Reopening as @gman0 is still not added to the team

**Comment by leseb** [comment]
I just added @gman0 to the contributors.

**Comment by Madhu-1** [comment]
> I just added @gman0 to the contributors.

Thanks @leseb

**Comment by humblec** [comment]
> I just added @gman0 to the contributors.

Thanks @leseb

**Comment by gman0** [comment]
Thank you all.
