### ISSUE TITLE
csi-rbdplugin - find fastest node?

### ISSUE THREAD

**Issue by rsoika** [ceph/ceph-csi#2385]
Is am using the csi-rbdplugin which works fine, but I have a question about the following architecture problem:

I am running ceph nodes in different data centres and also the kubernetes worker nodes in different data centres.

In each data centre there is a ceph node and a kubernetes worker node. Within a data centre I have a network bandwith of 1Gbit/s which works fine. Between the different data centres I have a network bandwith with about 500Mbit/s

Does the ceph csi-rbdplugin find the fastest (local) ceph node in the same data center or can it happen, that the plugin choses a node in a different datacenter which would result in a slower connection I guess? (All data centres have the same replicas)

I know form cassandra that a cassandra client checks the connection to all nodes first and tries to read the data always from the fastest node (in my case this would be the node in the same data centre). And I wonder if this mechanism is also implemented in ceph / ceph-csi?

**Comment by humblec** [comment]
@rsoika by default no such criteria has been applied by the ceph csi rbd plugin driver , the close solution which we can think of here is making use of topology aware provisioning ( #760 ) available with ceph csi. can you check this can help   ?

**Comment by rsoika** [comment]
Thanks for your reply. I tried to follow the discussions, but I am not sure if I am able understand the details. 
Is it possible, in some way, to define that the csi-plugin chooses a node within the same zone  (I understand a zone as an equivalent to a data centre) as the POD is running? 

For example:

My Ceph Cluster is running nodes in all zones and the pool is replicated over all zones. 

1. POD is scheduled on a worker node in ZONE-A
2. the csi plugin connects the pvc/pv with a (existing) static volume on a OSD within ZONE-A
3. for some reason zone-a goes down
4. Kuberentes reschedules the POD on a worker node in ZONE-B
5. the csi plugin connects the pvc/pv with a (existing) static volume on a OSD within ZONE-B


I guess this is all nonsense, because at the end, Ceph need to sync all nodes on a write request. This means my ceph cluster is in any case very slow (depending on the network speed between the data centers). So it does not matter if csi-plugin chooses a osd in the same zone or not - right?

**Comment by nixpanic** [comment]
You are correct that for writing there will be no improvement when the OSD local to the site will be used, it is required to write and acknowledge the data on remote OSDs as well.

It's been a while since I had to understand this, so take the following as super simplified and possibly not-100%-correct:
One RBD image is split into many objects. The location of an object is calculated into a Placement Group, and that Placement Group assigns a primary OSD and followers. Reads and writes go to the primary OSD first, and then get replicated (in case of writes) to the followers. The primary OSDs are distributed, so that the load of in the cluster is balanced over all OSDs. That also means some of the objects are read from the local OSD, others from remote OSDs.
There is a thing called [crush map](https://docs.ceph.com/en/latest/rados/operations/crush-map/) in Ceph, and that can configure a lot of the behaviour for reading/writing. For requests like this, it is better to search through or ask on the [Ceph Users mailinglist](https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/).

Let us know if you found this helpful, and if you were able to solve your question. Thanks!

**Comment by rsoika** [comment]
Thanks a lot for clarifying.  This helps me to understand better the architecture.

**Comment by Yuggupta27** [comment]
Thanks @rsoika , feel free to close the issue if your query has been answered, let us know if there is anything else we can help with!
