### ISSUE TITLE
unit testing failing for missing cluster-id

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2528]
```
=== PAUSE TestGetMappedID/test_for_invalid_match
=== CONT  TestGetMappedID/test_for_matching_key
=== CONT  TestFetchMappedClusterIDAndMons/test_missing_cluster_id=cluster-6
E0920 20:32:49.567135    8203 cluster_mapping.go:178] failed getting mons with cluster id "cluster-6": missing configuration for cluster ID "cluster-6"
=== CONT  TestFetchMappedClusterIDAndMons/test_cluster_id=cluster-4
=== CONT  TestFetchMappedClusterIDAndMons/test_cluster_id=cluster-3
```

https://github.com/ceph/ceph-csi/pull/2525/checks?check_run_id=3656180602

**Comment by nixpanic** [comment]
This is just an error message that is reported while testing, the tests do not fail due to this.

The linked run https://github.com/ceph/ceph-csi/pull/2525/checks?check_run_id=3656180602 causes a failure while compiling tests because of conflicting vendored dependencies (should get addressed with the related PR).
