### ISSUE TITLE
merge all fixes into master

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-csi#255]
Would you please merge all fixes into the "master" branch? We have two branches in GitHub currently:

1. `master`
2. `csi-v1.0`

I would expect the default branch (remote HEAD) to point to `master`, but it currently points to `csi-v1.0`.

This makes me think `csi-v1.0` must be some kind of long-lived feature branch, moving ahead of master in some ways, and behind master in other ways?

It's not clear to me which branch we should distribute downstream. It would make it easier for newcomers if "master" was the very latest, since this matches other repositories (like ceph.git) and rook.git).

**Comment by rootfs** [comment]
I'd think rename the branches so that:

- csi-v1.0 (current default) becomes the "new" master
- current master (i.e. csi v0.3 support) becomes new csi-v0.3 branch.

**Comment by gman0** [comment]
@rootfs i thought csi-v1.0 will stay in alpha until we sort out all the metadata-related issues?

**Comment by ShyamsundarR** [comment]
As this has come up in a couple of other conversations posting my thoughts as well,

- Although we state v1.0 branch is alpha, the images from these branches are available for use by users, is there a definitive statement we can make regarding v1.0's alpha status?

- The kubernetes driver [list](https://kubernetes-csi.github.io/docs/drivers.html) carries ceph drivers as v1.0, does this mean anything more than, these drivers are available for testing, and not for production/serious use? 

- If v1.0 is still in alpha, can we get breaking changes into the same, so that certain aspects need not be supported in the future (assuming we have a fair discussion about the same)

Not attempting to hijack the original thread, but some questions that crop up as we decide if v1.0 is still alpha.

My opinion is it (v1.0) should be alpha, till we can get a few things sorted out and also some CI or testing ironed out, to get to a required and sustainable quality as we add more code in the future.

**Comment by humblec** [comment]
@ktdreyer merging all the changes from CSI v1.0 branch to master is not possible because of the spec it maintains. ie master is on v0.3 and csiv1.0 is v1.0.0.  I think the best bet would be what @rootfs suggested. however, I doubt it can have some impact on the users who already cloned these repos and using it .

**Comment by ktdreyer** [comment]
Ok. Can we make `master` the mainline for development at least?

**Comment by Madhu-1** [comment]
@rootfs ^^

**Comment by humblec** [comment]
> Ok. Can we make `master` the mainline for development at least?

Sure, the only concern here is, how is it going to effect the existing customers if we do branch flip/switch..  @rootfs @gman0 can you share your thoughts?

**Comment by rootfs** [comment]
@ktdreyer @humblec let's cut a v0.3 branch from master, then reset master to replicate v1.0 branch, and then make master the dev branch.

**Comment by humblec** [comment]
@rootfs sounds good to me. Just to make sure, we are in same page, if some users already have the image from current master and if their CO is on a version which is compatible with `0.3` spec, after our update of master branch, do you foresee any issues ?

**Comment by rootfs** [comment]
There will be some CI work for 0.3 branch [here](https://github.com/ceph/ceph-csi/blob/csi-v1.0/.travis.yml#L12)

@Madhu-1 can you take all these? thanks

**Comment by Madhu-1** [comment]
@rootfs, sure let me check what changes i need to make.

**Comment by j-griffith** [comment]
proposal here #266

**Comment by j-griffith** [comment]
@Madhu-1 @humblec Sorry I started a discussion on this topic at #266 not realizing you had this going here.  I set what I was thinking in terms of a task-list, let me know what you think; if we get a branch csi-v0.3 branch I'm happy to help out with the remaining tasks.

**Comment by Madhu-1** [comment]
@ktdreyer @j-griffith can we close this one or #266 so that we can continue our discussion on one place so that we don't need to track the same issue in different places.

**Comment by humblec** [comment]
I would rather keep this open and close #266 considering this came first. @ktdreyer @j-griffith @Madhu-1 .

**Comment by Madhu-1** [comment]
anything would be fine for me. let  @ktdreyer and @j-griffith decide.

**Comment by Madhu-1** [comment]
closing this one as a master is the default brach
