### ISSUE TITLE
Can't pass any map options to rbd map

### ISSUE THREAD

**Issue by Nefelim4ag** [ceph/ceph-csi#291]
https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/rbd/rbd_attach.go#L295-L300

As example we use that options to pass: `osd_request_timeout=300,queue_depth=1024`

**Comment by Madhu-1** [comment]
@Nefelim4ag currently we don't support passing extra options to rbd commands. 

@rootfs @gman0 @ShyamsundarR do we need to consider this use case?

**Comment by rootfs** [comment]
yes, csi mount option supported in kubernetes https://github.com/kubernetes/kubernetes/pull/67898

**Comment by ShyamsundarR** [comment]
The options mentioned (osd_request_timeout, queue_depth) seem to be rbd options that have to be passed to the `rbd map` command when using the krbd client. Possibly other clients also support these options in different ways, but my investigation has been till [krbd](http://docs.ceph.com/docs/mimic/man/8/rbd/#kernel-rbd-krbd-options) client.

The code that you link to also points to `rbd map` so we are in sync till here as to who the options should be passed to.

Now, when I trace the [mount options](https://kubernetes.io/docs/concepts/storage/storage-classes/#mount-options) from the StorageClass to the in tree attacher for rbd (i.e what exists outside the scope of CSI till now), I see that these mount options are passed to the [FS mounter](https://github.com/kubernetes/kubernetes/blob/98e41b7038a3333f72e1ab19b6c6346143f18aa4/pkg/volume/rbd/attacher.go#L176) rather than the [rbd map](https://github.com/kubernetes/kubernetes/blob/98e41b7038a3333f72e1ab19b6c6346143f18aa4/pkg/volume/rbd/rbd_util.go#L219) command.

Thus, I do not understand if your request is to support RBD map options, or that these were supported in the past and we need to continue supporting them in the future. As I do not see them as supported in the past.

@Nefelim4ag Request clarification on the same.

Further, from the use-case of mount options, we should rightly be passing this to the FS mounter, and we [are](https://github.com/ceph/ceph-csi/blob/ac9b656d8117b9f08ae8114a5b4c5bee2b7beb4a/pkg/rbd/nodeserver.go#L148) in the CSI plugin as well. This cannot be overloaded to add RBD mount options IMO.

If the request is that the RBD CSI plugin should support RBD options in addition to existing options, we may need to consider this as a new option to be added to the StorageClass and evaluate the same.

**Comment by ShyamsundarR** [comment]
> Further, from the use-case of mount options, we should rightly be passing this to the FS mounter, and we [are](https://github.com/ceph/ceph-csi/blob/ac9b656d8117b9f08ae8114a5b4c5bee2b7beb4a/pkg/rbd/nodeserver.go#L148) in the CSI plugin as well. This cannot be overloaded to add RBD mount options IMO.

Correction as noted in issue #292 the mount options are not currently passed to the FS mounter.

@Nefelim4ag based on the other issue filed, I assume that this request is for rbd map options, that is separate from the mount options?

**Comment by Nefelim4ag** [comment]
@ShyamsundarR, yep
That request for pass options to `rbd map`

**Comment by humblec** [comment]
This has to be considered. With different map options coming along ( readonly, noudev..etc), we should make it configurable and at times pass these options for dynamic mapping of RBD devices at time of NODE mapping.
