### ISSUE TITLE
Mount modprobe from host/node to csi-rbdplugin container

### ISSUE THREAD

**Issue by kadasatya** [ceph/ceph-csi#3251]
# Describe the bug #

Mounting /user/sbin/modprobe from host to csi-rbdplugin container. The modprobe in csi-rbdplugin container does not support .zst. We are using zsdt algorithm for compression. So, the modprobe in csi-rbdplugin container not able to extract rbd.ko.zst. 

Either modprobe in csi-rbdplugin must be upgraded or mount it from host.

# Environment details #

- Image/version of Ceph CSI driver :
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version :
- Ceph cluster version :

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Logs #

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by nixpanic** [comment]
This is not trivial, as on many (if not all) systems, `modprobe` is a dynamically linked executable:

```console
$ ldd /usr/sbin/modprobe 
	linux-vdso.so.1 (0x00007ffe317fd000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007fa562b14000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fa562ae9000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fa562acf000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007fa562600000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa562aaf000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa562200000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa562c06000)
```

The Ceph-CSI project uses the `ceph/ceph:v17` image as base. In order to get a new `modprobe` in the container-image, the Ceph base layer needs to provide it. Currently `ceph/ceph:v17` uses CentOS Stream 8 as it's OS container-image.

If the Ceph base image can consume CentOS Stream 9, the version of `modprobe` might support the `.zst` format.

See ceph/ceph-container#2033 for a similar report.
