### ISSUE TITLE
Docker image tags being rolled

### ISSUE THREAD

**Issue by hyperbolic2346** [ceph/ceph-csi#345]
In trying to debug an issue I was having, I noticed that the v1.0.0 docker image is constantly rolling https://quay.io/repository/cephcsi/rbdplugin?tab=history. This makes it hard to have a working setup because the image keeps changing and possibly breaking. Is there a way to tag some stable docker images so that one can rely on them for testing and rollout? I don't see a stable tag for the v1 alpha release and v0.3.0 is only a month old, which could indicate the same thing going on there.

**Comment by ShyamsundarR** [comment]
Thanks, we are aware of this and is handled in [master](https://github.com/ceph/ceph-csi/pull/302). As we firm up the [release process](https://github.com/ceph/ceph-csi/pull/302#issuecomment-481296073), let me backport relevant changes from the same to the 1.0 branch, so that in the future the 1.0 image is not updated for each PR.

**Comment by hyperbolic2346** [comment]
@ShyamsundarR Thank you for this update. Good to know you're aware and working towards a solution here.
