### ISSUE TITLE
atomic container tagging

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#367]
The released container tag is updated with a different version of the container. This prevents Kubernetes from properly ensuring consistency between all cluster members and performing upgrades and rollbacks. We need a way to guarantee that a tag is not overridden, but instead a new tag is created.

**Comment by ktdreyer** [comment]
Could you please give an example of this problem?

**Comment by BlaineEXE** [comment]
I believe the problem statement is that a container is released, for example as `cephcsi/cephcsi:vX.Y.Z`. When there is an update to the code, a container is built, and that code is built into a container with the same tag `cephcsi/cephcsi:vX.Y.Z`. This is bad, because now users can be running old versions and new versions of the same container in production environments. Any update to containers for whatever reason should have a totally new tag.

**Comment by Madhu-1** [comment]
this is fixed now, on each release we are tagging the container with vX.Y.Z. the same container will not be updated
