### ISSUE TITLE
ceph-csi metrics 

### ISSUE THREAD

**Issue by Daniel-Pivonka** [ceph/ceph-csi#371]
Ceph-csi should collect metrics about grpc response times. These metrics could be useful for setting timeout values that could prevent creating endless loops (#284). We will also be able to see how the system response time is affected by a large amount of requests.

In addition to the response time this will allow us to build in other metrics in the future.

Here are a few examples of other metrics we could collect:
type of requests coming in 
counts of certain types of request
size of volumes requests
amount of snapshots

Through the use of a UnaryInterceptor already in place grpcs requests can be intercepted and collected to made available to a metrics collection system such as Prometheus or dump to logs.

**Comment by humblec** [comment]
@Madhu-1 @ShyamsundarR @phlogistonjohn PTAL

**Comment by Madhu-1** [comment]
i will work on this
/assign @Madhu-1

**Comment by Madhu-1** [comment]
@Daniel-Pivonka are you working on this PR?

**Comment by Daniel-Pivonka** [comment]
@Madhu-1  yes ive started some work on this already

**Comment by Madhu-1** [comment]
@Daniel-Pivonka Thanks, assigning this to you as you are already working on this

**Comment by ShyamsundarR** [comment]
@Daniel-Pivonka as investigated we should possibly use https://github.com/grpc-ecosystem/go-grpc-prometheus instead of writing our own interceptor, as the other one seems richer in what it provides. Other intentions of how to integrate this with ceph-csi remains the same.

**Comment by humblec** [comment]
@Daniel-Pivonka I believe this is taken care now. Closing for the same reason. :+1:

**Comment by Madhu-1** [comment]
@humblec this is not done yet reopening

**Comment by Madhu-1** [comment]
having  https://github.com/grpc-ecosystem/go-grpc-prometheus interceptor seems heavy and also provides a lot of information which is not relevant,  it also doesn't provide info like total time spent on a particular request.  I would like to see below information in metrics

Request type, request unique ID, time spent on request, the total number of request received, the total number of success, failed requests, etc 

if we implement our own interceptor we can add if we need extra information later also. 

@ShyamsundarR @humblec I hope with this information we can check the time consumed per request in larger eco-system.

**Comment by Madhu-1** [comment]
am still thinking do we need to implement metrics at all, I would suggest using some shell script to fetch the logs, and grep for the request ID. one thing we need to do is to log the time taken for the request.
this will avoid the running metrics server in cephcsi

**Comment by ShyamsundarR** [comment]
There are a few points made here, so segregating them to the best of my understanding and responding on what we need.

1. Metrics

The intent of metrics is not to provide per-operation times and such, it is a broader set of statistics that can help set monitors and triggers for possible failures or latency etc. Hence gathering per operation or request-id times are an overkill for metrics.

What the gRPC prometheus interceptor provides are essentially RPC metrics, that help in this regard. Further, it helps when we gather the latency details for the RPCs as well, using the `EnableHandlingTimeHistogram` as that helps answer or set triggers for any slowness in the system.

2. Granular troubleshooting

This is where we need to get into logs and trace out a single request because of issues with the same. This is still needed, but these do not cover metrics needs, these are for troubleshooting specific issues instead. With context based logging being worked on, this becomes easier to do.

Further, if these are sent to a logging server, it makes it easier to look at them across nodes and services (this is orthogonal to the current discussion)

3. Extensibility

When we need to provide our own additional metrics to prometheus, we can add another endpoint to handle `http.Handle`, so using gRPC prometheus metrics does not preclude or prevent future expansion in the same arena.

Using gRPC prometheus metrics does cover a large part of what we need though, and hence reinventing this does not seem prudent (from a stability, maintenance and other such perspectives)

4. Trade off between single service container and metrics for that service

Finally, I am not sure if this is being referred to in the comments, but the trade off between the guiding principle that a container should run only a single service, and efficiency of providing metrics from the service directly, needs to be weighed appropriately. IOW, it is far more efficient to expose the metrics from the plugin containers using a go routine, than forward the same to another side car and then publish the same (the gRPC prometheus examples also seem to suggest the same).

cc @JohnStrunk @raghavendra-talur @phlogistonjohn
