### ISSUE TITLE
Use specific ceph image tag when doing cephcsi release.

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4001]
Currently, we are using tags like `v15` for the ceph image. this always pulls the latest ceph image, if there is a bug introduced with the latest images and if someone tries to build the cephcsi released branch/tag based on the above image we can get consistence builds.

To solve this problem lets stick to the exact `vx.y.z` tag of the ceph image when doing the ceph csi release.

**Comment by nixpanic** [comment]
The problem with this is, that users do not get the Ceph bugfixes when rebuilding the image... Users for production deployments should probably rebuild the images for their environment in any case, so that the Ceph versions match for all the different components.

I do not think there is a real good solution for this in community managed builds.

**Comment by Madhu-1** [comment]
> The problem with this is, that users do not get the Ceph bugfixes when rebuilding the image... Users for production deployments should probably rebuild the images for their environment in any case, so that the Ceph versions match for all the different components.
> 
> I do not think there is a real good solution for this in community managed builds.

This solves the having consistent build at least on the released branch if we need a new build to get ceph fixes that should come as a patch release (anyway)

**Comment by Madhu-1** [comment]
Closing this one, as discussed in yesterday's meeting. achieving consistent builds is not possible due to the external dependency in the base image and also we don't run `update` and install a few packages in the base image.
