### ISSUE TITLE
Update csi migration page

### ISSUE THREAD

**Issue by msau42** [ceph/ceph-csi#4054]
# Describe the bug #

Now the the Kubernetes CSI migration feature for RBD is being abandoned, we should replace this page with some manual steps on how to convert an intree volume to a CSI volume: https://github.com/ceph/ceph-csi/blob/devel/docs/intree-migrate.md

**Comment by Madhu-1** [comment]
@humblec do you have any plan to work on it?

**Comment by humblec** [comment]
@Madhu-1 I will get the documentation adjusted accordingly.

**Comment by humblec** [comment]
working on it.

**Comment by humblec** [comment]
@subhamkrai as discussed I am clubbing some content between the migration and restore options.. will send it as draft for review before pushing it here..

**Comment by subhamkrai** [comment]
@Madhu-1 do we need this issue? I thought everything was documented earlier at least I remember from the rook side we had docs https://github.com/rook/rook/pull/9222/files and everything. what new we are planning to add to this?

**Comment by humblec** [comment]
> @Madhu-1 do we need this issue? I thought everything was documented earlier at least I remember from the rook side we had docs https://github.com/rook/rook/pull/9222/files and everything. what new we are planning to add to this?

one thing which I did here is this : pointing the migrator utility from the in-tree doc. 

https://github.com/ceph/ceph-csi/pull/4221

So that folks can use the same to get the conversion on going in their old cluster. 

But @subhamkrai , we need some help to have an example or demo of `kubernetes.io/rbd` provisioner to `Ceph-csi` migration path in the utility too. We had it as a demo, however we only have flex volume information in the same.. I need help from your end to populate the same information in the utility doc

**Comment by subhamkrai** [comment]
> > @Madhu-1 do we need this issue? I thought everything was documented earlier at least I remember from the rook side we had docs https://github.com/rook/rook/pull/9222/files and everything. what new we are planning to add to this?
> 
> one thing which I did here is this : pointing the migrator utility from the in-tree doc.
> 
> #4221
> 
> So that folks can use the same to get the conversion on going in their old cluster.
> 
> But @subhamkrai , we need some help to have an example or demo of `kubernetes.io/rbd` provisioner to `Ceph-csi` migration path in the utility too. We had it as a demo, however we only have flex volume information in the same.. I need help from your end to populate the same information in the utility doc

I'm not sure how exactly I'll be able to help here, the PR link has the doc which includes all the details to migrate. We created it a long time ago and since then use case was over we reverted/ removed the docs from the later version of rook. I forgot the implementation details but once you create the PR, let me know in the pr where I can help as it's a long time back I'll also need to look again. Thanks for looking into this.
