### ISSUE TITLE
Remove code for Protect/Unprotect snapshot in CephFS

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4169]
Based on the supported ceph version, check the feasibility of removing the protect/unprotect code https://github.com/ceph/ceph-csi/blob/cba5402ac27eb0e732d09743bf3480d0ad5a9e1b/internal/cephfs/core/snapshot.go#L177-L244

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/blob/cba5402ac27eb0e732d09743bf3480d0ad5a9e1b/internal/cephfs/controllerserver.go#L838-L843 This comment and its relavent code can also be removed

**Comment by iPraveenParihar** [comment]
I'll take a look at this.

**Comment by iPraveenParihar** [comment]
From docs - https://docs.ceph.com/en/latest/cephfs/fs-volumes/#cloning-snapshots

Protecting snapshots prior to cloning was a prerequisite in the `Nautilus` release, and the commands to protect/unprotect snapshots were introduced for this purpose. This prerequisite, and hence the commands to protect/unprotect, is being deprecated and may be removed from a future release.

The commands being deprecated are:
```
ceph fs subvolume snapshot protect <vol_name> <subvol_name> <snap_name> [--group_name <subvol_group_name>]
ceph fs subvolume snapshot unprotect <vol_name> <subvol_name> <snap_name> [--group_name <subvol_group_name>]
```
---

Since, we have support >=Octopus we can remove the protect/unprotect code.
@Madhu-1

**Comment by Madhu-1** [comment]
Even Octopus is EOL, IMO we can remove the above code.
