### ISSUE TITLE
cephfs-csi Pod has always been in containercreating

### ISSUE THREAD

**Issue by kisylike** [ceph/ceph-csi#4667]
Warning  FailedMount  4s  kubelet  MountVolume.MountDevice failed for volume "pvc-badb0e0a-8c85-4e78-a28c-6bc6d1b0b765" : rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 10.10.40.100,10.10.40.101,10.10.40.102:/volumes/csi/csi-vol-a79d30e4-ba30-4cb5-903d-0b12fd70527c/a6be756c-1f19-4aab-83ad-c6daf2cd5d49 /var/lib/kubelet/plugins/kubernetes.io/csi/cephfs.csi.ceph.com/56ba6dc03b41250c215388cb53ed766f349e90b07a5830514dceea98fed41ad3/globalmount -o name=admin,secretfile=/tmp/csi/keys/keyfile-511267348,mds_namespace=cephfs,discard,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon
2024-06-06T07:57:50.394+0000 7f44149d9140 -1 failed for service _ceph-mon._tcp
![屏幕截图 2024-03-19](https://github.com/ceph/ceph-csi/assets/138099635/2264071f-4399-4be0-b669-c61c2640e2fb)

**Comment by nixpanic** [comment]
Please check the [issue template](https://github.com/ceph/ceph-csi/blob/devel/.github/ISSUE_TEMPLATE/bug_report.md) that was part of the initial contents of the issue that you created.

You will need to provide at least the logs for the csi-cephfsplugin container on the node where the mounting of the PV failed. Include the logs for the creation of the PV woul help as well, so that can be traced how that was done, and how it could go wrong while mounting.
