### ISSUE TITLE
Allow custom volume prefix for Ceph {FS && RBD }CSI volumes

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#487]
# Describe the feature you'd like to have #

What new functionality do you want?

As an admin I would like to create custom volume name prefixed volumes via Ceph CSI. There is an option for `volumenameprefix` per driver, but that is not getting tracked here, rather by this issue, we are looking for an option to specify volumename prefixes via SC for CephFS and RBD volumes.

# What is the value to the end user? (why is it a priority?) #

In a setup where you have many volumes, by this functionality admin can filter volumes based on this prefix.

# How will we know we have a good solution? (acceptance criteria) #

Create volumes with different prefixes and list/filter the volumes on a particular filter.

**Comment by Madhu-1** [comment]
same applies for a snapshot also

**Comment by humblec** [comment]
> same applies for a snapshot also

Sure, we could start with volumes first.

**Comment by ShyamsundarR** [comment]
Is it not feasible to just filter PVs provisioned using a named storage class, and then using the `volumeID` to list the image names backing these PVs?

This way the same scripts/applications that help trace a PVC all the way to a image can be reused with this and other such use-cases. Also, removes the need to add extra parameters to the storage class to track names or other such information.

Tagging @phlogistonjohn and @raghavendra-talur for thoughts on this.

**Comment by raghavendra-talur** [comment]
@ShyamsundarR @Madhu-1 @humblec IMO, overloading the name with a filtering requirement would be less flexible thing to do. Based on what we have learnt from gluster and heketi we know:

1. Getting a list of PVs and PVCs backed by a storageclass is very easy both using the API and by using go templates in cli.
2. It is much more flexible if such attributes which may be required for filtering are placed as key/value pairs(labels) on the resources than prefixing/suffixing them in the name. 

If the labels are stored in both the kubernetes side(in PVs spec) and *also* passed down to the ceph as some user provided attributes it would tie things up very well.

**Comment by skoef** [comment]
I would like to see such a feature as well. I'm not interested in filtering the PVs whatsoever, I need such a feature to integrate with an already existing ceph management plane we have running. I think there are two things we could understand by custom volume prefixes:

1. a `--volume-name-prefix` flag, just like the CSI provisioner has. This would only allow you to customise the default `csi-vol-` prefix, applied to all volumes.
1. a way to have a completely different name, albeit prefixed, for each volume. I was fiddling with the CSI provisioner earlier today to include the PVC's name into the PV name. This would lead to something like `pvc-myclaim-4ed0285e-8429-47f5-b9ac-2128048f30a4` where `pvc` would be the prefix, `myclaim` the name of the PVC and the suffix the UID it is given anyways. This would integrate perfectly with our backend systems, since that already keeps a UID per volume.

In both cases I think it is important to, obviously, be backwards compatible with a prior situation in which you didn't have the features enabled yet.

I would like to make a suggestion for both options in the coming days.

**Comment by skoef** [comment]
Basically, what I think i need to do is create an additional omap key, `csiImageKey`, to store the rbd image name that corresponds to that volume. That way, when you change image name prefixes at some point, or base the image names on something different, the volume always point to the image name it got when it was created.
