### ISSUE TITLE
Detect `rbd map` timeout errors and detect if image is mapped, to undo the mapping

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#520]
It is noted that there are cases when,
- `rbd map` invocation times out #507 
- It leaves behind a mapped image to a device (because mapping actually completed, but state/success of the same was missed out)

This causes future attempts to map the image on other nodes, or attempts to delete the image, to error out stating image is in use.

This issue is being opened to add some safety checks and workarounds in the code, that will detect such timeout errors, and check to see if the image is mapped to a device, and undo the same.

NOTE: as we do not know the device path when rbd map returns a timeout failure, it may need the current PR #510 work to complete to leverage the detection of device using `rbd device list` instead of current schemes.

**Comment by Madhu-1** [comment]
I think we can call unmap with image name also, why to wait for #510?

**Comment by idryomov** [comment]
Yes, "rbd unmap" supports unmapping by image name.  No need to list mapped images just for that.

**Comment by ShyamsundarR** [comment]
Ack! was not aware of that. We should use imagespec instead of hunting for the devicePath. Also, I assume this is true when `--device-type` is nbd?

**Comment by dillaman** [comment]
> Ack! was not aware of that. We should use imagespec instead of hunting for the devicePath. Also, I assume this is true when `--device-type` is nbd?

Yes, with the caveat for both where it doesn't handle different clusters.

**Comment by idryomov** [comment]
@ShyamsundarR Yes, it should be true.

I'm not sure I understand the need to unmap the device in this case.  If "rbd map" times out because udev decided to take a break but the device is there (i.e. you listed mapped images and got the device node), would pretending that nothing happened not work?

If we keep encountering issues with udev, we could probably adopt this course of action for the general case as well -- make "rbd map" wait for udev for a much shorter period of time and then instead of immediately bailing with a timeout error, try to get the device node by listing the devices.

**Comment by idryomov** [comment]
> Yes, with the caveat for both where it doesn't handle different clusters.

This is another thing that I don't fully understand.  I thought we controlled image names in CSI?  In https://github.com/ceph/ceph-csi/pull/510#issuecomment-516074646 @ShyamsundarR mentioned that we indeed do use UUIDs there, but the discussion continued with various workarounds...

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR Yes, it should be true.
> 
> I'm not sure I understand the need to unmap the device in this case. If "rbd map" times out because udev decided to take a break but the device is there (i.e. you listed mapped images and got the device node), would pretending that nothing happened not work?

So the manner in which kubernetes (and possibly other container orchestrators) behaves (and also laid out in the [spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#timeouts) around timeout handling of various RPCs), is as follows,
- Call NodeStageVolume with a timeout of `t1`
- If call timed out, wait for some exponential backoff time `t2`
- Call NodeStageVolume again
- Bail out at some point in time from calling NodeStageVolume, because the workload moved to a different node, and kubernetes never got a success back for any of its calls (there is a race window here, irrespective of what we fix, in kubernetes, but we will pretend for the moment that it is not so)
  - As, a result never call NodeUnstageVolume for the same image (which would result in a leak of the image map)

In our case, if the first call "hangs" due to various reasons, its success/failure result from the RPC response maybe ignored if `t1` is past. Hence leaving behind a mapped rbd device is not a desired resolution. It all depends on the timeout, which the plugin is unaware of (IOW, there are no call cancels, so the plugin will not know the RPC was cancelled/timedout).

> 
> If we keep encountering issues with udev, we could probably adopt this course of action for the general case as well -- make "rbd map" wait for udev for a much shorter period of time and then instead of immediately bailing with a timeout error, try to get the device node by listing the devices.

We could, but I am not comfortable deciding the timeout values to closely resemble or be lower than the kubernetes/CO timeouts and hence make this work within such slices.

Beyond above discussion, we could/should still add a timeout to detect udev (or other) hangs/failures faster (or use this to "fail fast") and hence prevent 2-10 minute hangs that we have seen.

**Comment by ShyamsundarR** [comment]
> > Yes, with the caveat for both where it doesn't handle different clusters.
> 
> This is another thing that I don't fully understand. I thought we controlled image names in CSI? In [#510 (comment)](https://github.com/ceph/ceph-csi/pull/510#issuecomment-516074646) @ShyamsundarR mentioned that we indeed do use UUIDs there, but the discussion continued with various workarounds...

So the caveat here is that IF there are 2 images with the same poolname and imagename, but from different ceph clusters, imagespec based commands are inadequate to identify which image we are referring to.

The workaround or statement to say this will not happen, is that we use UUIDs to name the image, and this collision across cluster hence needs a UUID collision to occur as well, and that is mathematically very rare etc.

**Comment by idryomov** [comment]
(I might be talking nonsense here because I'm not familiar with CSI RPCs, please bear with me.)

> In our case, if the first call "hangs" due to various reasons, its success/failure result from the RPC response maybe ignored if `t1` is past. Hence leaving behind a mapped rbd device is not a desired resolution. It all depends on the timeout, which the plugin is unaware of (IOW, there are no call cancels, so the plugin will not know the RPC was cancelled/timedout).

This makes me slightly concerned about the reliability of the system, but the fact that these RPCs must be idempotent is even more reason for UUID-based image names.  If the CO doesn't always cancel pending operations, stale mappings are unavoidable.

I guess I don't see why leaving behind a mapped device in this case is undesirable.  If "rbd map" times out but the device node is there, you send back a success.  If your reply is ignored and you get a retry, you can satisfy it immediately because the image with that (globally unique) name is already mapped.  If your reply is ignored and you don't get a retry (e.g. because the workload was moved to a different node by the CO), you get a stale mapping.  But it sounds like stale mappings/images/etc is something that the plugin should be prepared to deal with anyway because they are pretty much written into the spec...

> Beyond above discussion, we could/should still add a timeout to detect udev (or other) hangs/failures faster (or use this to "fail fast") and hence prevent 2-10 minute hangs that we have seen.

Unfortunately, the 2 minute timeout in "rbd map" is not on the overall interaction with udev, but on the individual poll() call.  So in a scenario where multiple images are getting mapped concurrently and udev is really slow for whatever reason, "rbd map" could theoretically sit there for hours -- as long as udev keeps delivering events at a rate of ~0.5/minute.

What version of ceph were you testing with?  For 10 minute hangs, was that on 14.2.2 or something prior?

**Comment by Madhu-1** [comment]
I have a dumb question, do CSI has to bother about the timeout error and handle it specially. it should be the client work to unmap the image if timeouts right?

@idryomov we can add some default timeout for rbd map command I will check whats the timeout for RPC call from Kube side. this should fix the timeout issue I believe

@idryomov any preferred timeout option from rbd side. as we don't know the image size, I think larger the image size it takes more time to map right?

@humblec ^^

**Comment by idryomov** [comment]
> @idryomov we can add some default timeout for rbd map command I will check whats the timeout for RPC call from Kube side. this should fix the timeout issue I believe

As @ShyamsundarR said, we probably don't want to tune our timeout (be it at a higher level in the plugin or at a lower level in "rbd map"/"rbd unmap") to various kubernetes timeouts because this is not reliable, both in general and (especially) at scale.

> @idryomov any preferred timeout option from rbd side. as we don't know the image size, I think larger the image size it takes more time to map right?

No preferences, I would pick one based on test results on real hardware.

Currently, with just layering supported, the size of the image is completely irrelevant.  In the future, when we start supporting object-map and fast-diff, it might be a little more noticeable because the size of the object map is proportional to the size of image, but it is certainly not something that should be taken into account.  The timeout should be the same in all cases.

**Comment by Madhu-1** [comment]
is there a way to handle this as this action belongs to rbd map and udev to map the image on a node. as  @idryomov  said earlier what if udev takes a break and maps the rbd device on the node, this will become stale device on the node which we cant delete (need manual cleanup)

**Comment by idryomov** [comment]
> > I have a dumb question, do CSI has to bother about the timeout error and handle it specially. it should be the client work to unmap the image if timeouts right?
> 
> @idryomov your thoughts on this one?

I was deferring to @ShyamsundarR an @humblec because I'm not very familiar with CSI.  As I said in https://github.com/ceph/ceph-csi/issues/520#issuecomment-518263480, given the CSI spec, I think stale mappings/image/etc are unavoidable.

What is the client you are thinking of here?  The CO, the end user who just wants her PV, someone else?  If my reading of the spec is correct, only the plugin can be responsible for unmapping a stale mapping or removing a stale image because only the plugin has that information.  The CO may not have enough information to issue an "undo" RPC and on top of that the spec doesn't seem to require the CO to do that in all cases.

**Comment by Madhu-1** [comment]
@idryomov as you said above it purely depends on `udev` to map the rbd image on the node ( as you said it can take a break and map the image later also) do you think this need to be handled in the code?
if yes I would like to check how this can be handled whether do we need to start a goroutine periodically and check the device is stale or not, if yes mark it for unmapping.

@humblec @ShyamsundarR Thoughts?

**Comment by idryomov** [comment]
@Madhu-1 Are you referring to https://github.com/ceph/ceph-csi/issues/520#issuecomment-518263480 where I described a theoretical scenario for "rbd map" and udev?

A periodic check for stale images/mappings/etc sounds good, but it would be needed primarily to guard against the CO silently giving up and moving the workload to a different node, which is a separate issue.  The case of a CLI command taking forever (it could be any command that talks to RADOS, whether directly or indirectly through the kernel) is also separate -- it would likely take a per-invocation timeout in the plugin, but it is not clear to be that it is actually needed.  I'm generally wary of introducing arbitrary timeouts.

This particular ticket is about the unfortunate failure mode of "rbd map".  This timeout was slapped on as a poor workaround for a bug which has (hopefully) been fixed, so I think we should consider reverting it.  In any case, no need for an async goroutine here -- just look at the exit code or parse the error message, if it is a timeout, list the mappings and "rbd unmap" if needed.

**Comment by ShyamsundarR** [comment]
> In any case, no need for an async goroutine here -- just look at the exit code or parse the error message, if it is a timeout, list the mappings and "rbd unmap" if needed.

The above is what I would suggest as well, or maybe even checking if the device is mapped or not is optional, and we can issue a blanket unmap for the `image-spec`.

**Comment by Madhu-1** [comment]
> @Madhu-1 Are you referring to [#520 (comment)](https://github.com/ceph/ceph-csi/issues/520#issuecomment-518263480) where I described a theoretical scenario for "rbd map" and udev?
> 
> A periodic check for stale images/mappings/etc sounds good, but it would be needed primarily to guard against the CO silently giving up and moving the workload to a different node, which is a separate issue. The case of a CLI command taking forever (it could be any command that talks to RADOS, whether directly or indirectly through the kernel) is also separate -- it would likely take a per-invocation timeout in the plugin, but it is not clear to be that it is actually needed. I'm generally wary of introducing arbitrary timeouts.
> 
> This particular ticket is about the unfortunate failure mode of "rbd map". This timeout was slapped on as a poor workaround for a bug which has (hopefully) been fixed, so I think we should consider reverting it. In any case, no need for an async goroutine here -- just look at the exit code or parse the error message, if it is a timeout, list the mappings and "rbd unmap" if needed.
 
the image will be mapped immediately  if rbd map timeouts or it may take some time to map the image ( want to understand all the possible scenarios)

**Comment by idryomov** [comment]
If "rbd map" fails because of this udev timeout, the image is definitely mapped -- it doesn't wait for udev events unless the mapping succeeds.  However, I think the kernel can return ETIMEDOUT as well and in this case the image is definitely not mapped.  You can distinguish between these cases by parsing the error message: a mapping failure will always have "rbd: sysfs write failed" in it, any other failure (e.g. udev timeout) won't.

This is why I suggested listing the mappings.  You don't need to parse "rbd map" output (thus relying on it to stay the same) and if you see the mapping, you expect success from "rbd unmap".  If you "rbd unmap" unconditionally, you don't know what to expect: success or "not a mapped image" failure.

**Comment by Madhu-1** [comment]
Fixed in #561
