### ISSUE TITLE
Slow mounting of volumes with large files collections

### ISSUE THREAD

**Issue by dimm0** [ceph/ceph-csi#718]
# Describe the bug #

Kubernetes chowns and selinux relabels all files in mounted volumes, which causes very slow mounts of volumes with large files collections (100K+)

Everything is described here: https://github.com/kubernetes/kubernetes/issues/69699

Is there a way to disable this on CSI Ceph driver level?

**Comment by ShyamsundarR** [comment]
These cannot be disabled in CSI.

CSI did have a severe performance degrade when performing fsGroup changes, and this is fixed by this PR: https://github.com/kubernetes/kubernetes/pull/83747 (not sure which kube version it is part of though).

I have tested the above PR for around 90k files, it brings the attach time down from about ~330 seconds to about ~40 seconds. Your mileage may vary based on your setups, but relative performance should improve drastically.

**Comment by dimm0** [comment]
I have volumes with several millions files...
Is it also doing chown in cephFS volumes?

**Comment by afraserbm** [comment]
Is it possible to fix the issue within ceph-csi and not rely on having to implement v1.17 of Kube? We currently run kube 1.15.2 on our clusters so upgrading to that version is a long road. Disabling selinux entirely works and resolves the issue as described (at least for me running coreos) however this doesn't feel like the correct approach.

The issue has been addressed in the rook implementation here : https://github.com/rook/rook/pull/2219

**Comment by Madhu-1** [comment]
cc @humblec @JohnStrunk

**Comment by JohnStrunk** [comment]
Neither fsgroup, nor SELinux options are exposed through the CSI API. That all happens on the kube side. Regarding rook/rook#2219, that is for the old flexvol plugin that Rook used. The flexvol API **does** expose that info, unlike CSI.

The way kube makes the choice is:
* For fsgroup, it's based on fsType and RWO: https://github.com/kubernetes/kubernetes/blob/3994f52ee6bef7ea1572184ae0a31f3abeaa7469/pkg/volume/csi/csi_mounter.go#L379
* For SELinux, it's based on whether the mount has the "seclabel" option: https://github.com/kubernetes/kubernetes/blob/3994f52ee6bef7ea1572184ae0a31f3abeaa7469/pkg/volume/util/hostutil/hostutil_linux.go#L228

The implication here is that cephfs will not get fsgroup since it's RWX (@dimm0).

As of two weeks ago at kubecon, it appears the path forward for fsgroup is to make it optional by adding a field to v1.pod. That would permit the fsgroup change to be "always" (default & current behavior), "never", or "ondemand" (by checking if the root is correct). I'm not aware of a plan to fix SELinux.

**Comment by dimm0** [comment]
> The implication here is that cephfs will not get fsgroup since it's RWX (@dimm0).
🎈🎉🎉🎉🎉🎈🎉🎉🎉🎉🎈

**Comment by Madhu-1** [comment]
closing this one as its not a cephcsi issue.
