### ISSUE TITLE
Running "make containerized-test" always fails

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/ceph-csi#980]
# Describe the bug #

I can not run `make containerized-test` successfully at this time. It appears that shellcheck is checking a script `./tmp/get_helm.sh` that is not under control of the "ceph-csi" source control.

I have never run the tests non-containerized so perhaps that is why I am hitting this? I do realize that the make rule in question is fairly new.

# Environment details #

n/a

# Steps to reproduce #

Run `make containerized-test CONTAINER_CMD=podman` and it fails every time for me, both on master and my working branch.

**Comment by phlogistonjohn** [comment]
@nixpanic I am not sure why I am hitting this 100% but I am assuming you did not when you added this.

**Comment by phlogistonjohn** [comment]
Looks like a simple fix might be to exclude the "./tmp" directory assuming nothing else is expected to appear there. Let me know if you want to try and figure out why this didn't affect you or if you want me to just go and update the script regardless.

**Comment by nixpanic** [comment]
hmm, I do not have the `./tmp/get_helm.sh` script here... Running the containerized tests for all things I do with this repository.

I guess you ran `./deploy.sh` in the repository? That is a script that you do not need to run :smile: You should be able to remove the `./tmp` directory completely. If it was caused by `deploy.sh`, the script should be corrected to clean up after itself.

**Comment by phlogistonjohn** [comment]
I don't remember running deploy.sh, at least not w/in the last 6 months. It might be old, stale, stuff from when I last worked on ceph-csi many months ago. Deleting the ./tmp dir prevented the failure and it did not appear to get re-created. Hopefully @Madhu-1 change will prevent it from happening to other people in the future.
